ignore:
  urls:
    - https://aclanthology.org/*
    - https://alaginrc.nict.go.jp/nict-bert/index.html
    - https://arxiv.org/*
    - https://developers-jp.googleblog.com/2024/10/gemma-2-for-japan.html
    - https://gitlab.llm-jp.nii.ac.jp/datasets/*
    - https://llm-jp.nii.ac.jp/*
    - https://ojs.aaai.org/*
    - https://scholar.google.co.jp/*
    - https://scholar.google.com/*
    - https://www.anlp.jp/*
    - https://www.informatix.co.jp/pr-roberta/