ignore:
  urls:
    - https://aclanthology.org/*
    - https://alaginrc.nict.go.jp/nict-bert/index.html
    - https://arxiv.org/*
    - https://gitlab.llm-jp.nii.ac.jp/datasets/*
    - https://llm-jp.nii.ac.jp/*
    - https://ojs.aaai.org/*
    - https://www.anlp.jp/*
    - https://www.informatix.co.jp/pr-roberta/