name: Add contributors
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  add-contributors:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: BobAnkh/add-contributors@v0.2.2
      with:
        CONTRIBUTOR: '## Our Contributors'
        COLUMN_PER_ROW: '6'
        ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
        IMG_WIDTH: '100'
        FONT_SIZE: '14'
        PATH: '/README_en.md'
        COMMIT_MESSAGE: 'docs: update contributors (en)'
        AVATAR_SHAPE: 'round'