name: 404 Links Checker

on:
  pull_request:
    branches: ["main"]

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 'restqa-404-links'
      uses: restqa/404-links@3.1.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
